Add series endpoint
kundi/nightwatch-api-docs pull request #2
Opened 2019-07-19 12:23 UTC by matixmatix

2019-07-20 17:03 UTC, emnlvrz requested changes

2019-07-20 17:03 UTC, emnlvrz commented on source/endpoints/series.md.erb
> +url_ids   | Array of URL ids
`url_ids` is mandatory.

2019-07-20 17:03 UTC, emnlvrz commented on source/endpoints/series.md.erb
> +keyword_ids  | Array of keyword ids
`keyword_ids` is mandatory.

2019-07-20 17:03 UTC, emnlvrz commented on source/endpoints/series.md.erb
> +with_competitors | Include competititor URL series (true or false, default: true)
We name this option but we don't show an example, I think we should include a brief mention as they resemble a lot to URL series anyway.

2019-07-20 17:03 UTC, emnlvrz commented on source/endpoints/series.md.erb
> +
`up_down` series is missing.

2019-07-20 17:03 UTC, emnlvrz commented on source/endpoints/series.md.erb
> +
`up_down` is missing.

2019-07-20 17:03 UTC, emnlvrz commented on source/endpoints/series.md.erb
> +
Google Analytics series are missing:
 - `clicks`
 - `impressions`
 - `search_console_position`
 - `ctr`

Might be worth noting that if GA integration is not setup these series will be empty (`[]`). Same notice applies to URL series.

2019-07-20 17:03 UTC, emnlvrz commented on source/endpoints/series.md.erb
> +    ...
Maybe a word on competitor series?

2019-07-22 12:24 UTC, matixmatix commented on source/endpoints/series.md.erb
> +keyword_ids  | Array of keyword ids
Added the asterisk.

2019-07-22 12:25 UTC, matixmatix commented on source/endpoints/series.md.erb
> +with_competitors | Include competititor URL series (true or false, default: true)
Added the example.

2019-07-22 12:25 UTC, matixmatix commented on source/endpoints/series.md.erb
> +
Added.

2019-07-22 12:25 UTC, matixmatix commented on source/endpoints/series.md.erb
> +    ...
Added an example.

2019-07-22 13:11 UTC, emnlvrz approved these changes

2019-07-22 13:11 UTC, merged