Feature/view docs
kundi/nightwatch-api-docs pull request #7
Opened 2019-08-16 08:29 UTC by matixmatix

2019-08-16 13:32 UTC, emnlvrz requested changes
This API kinda sucks, specially the filter groups part. I would suggest adding *Get Filter Groups* and *Update Filter Groups* sections (like we do in *Create a view* section). Unless we plan to do the filter groups endpoint separately.

2019-08-16 13:32 UTC, emnlvrz commented on source/endpoints/views.md.erb
> +scope     | when group ID is not provided, this value has to be "account"
Description should start in capitals :smile:

2019-08-16 13:32 UTC, emnlvrz commented on source/endpoints/views.md.erb
> +### Presence and absence conditions
Should we add some words about to which fields this applies? Even if they apply to every  field, maybe? :thinking:

2019-08-16 13:32 UTC, emnlvrz commented on source/endpoints/views.md.erb
> +group_id  | views belonging to a specific group
Capitals :point_up:

2019-08-16 13:32 UTC, emnlvrz commented on source/endpoints/views.md.erb
> +scope     | when group ID is not provided, this value has to be "account"
Capitals

2019-08-19 15:51 UTC, jurgenwerk commented on source/endpoints/views.md.erb
> +### Presence and absence conditions
Yes. Good idea. Will add it.

2019-08-19 15:51 UTC, jurgenwerk commented on source/endpoints/views.md.erb
> +scope     | when group ID is not provided, this value has to be "account"
You're so meticulous 😍

2019-08-19 15:51 UTC, jurgenwerk commented on source/endpoints/views.md.erb
> +group_id  | views belonging to a specific group
Yesh

2019-08-19 16:37 UTC, merged